# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-dns-primary
  description: This component is responsible for provisioning the primary DNS zones into an AWS account
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component






